### ISSUE TITLE
obsolete reference to helpers.rb in README

### ISSUE THREAD

**Issue by regineheberlein** [lyrasis/archivesspace-client#11]
From the README: 

> See `helpers.rb` for more convenience methods such as `client.digital_objects` etc.

It appears this file has since been deleted from the repo? Would be helpful to restore and/or link it from the README.

**Comment by mark-cooper** [comment]
@regineheberlein thanks for pointing that out. That aspect of helpers was shuffled into pagination.rb. I'll give the README a look over this week/end.
